### ISSUE TITLE
[DDO] 참여취소 

### ISSUE THREAD

**Issue by leekyukin** [Bamdoliro/Gati-server#132]
### ✨ Describe

ddo 게시물에 참여했던 참여자가 참여를 취소할 수 있다.

### ✅ Tasks

- [x] 참여 취소 logic
- [x] 참여 취소 test
- [x] 참여 취소 validation
