### ISSUE TITLE
Community 참여하기

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/Gati-server#22]
### ✨ Describe

User가 Community에 참여할 수 있어야 합니다.

### ✅ Tasks

- [x] Member Entity, repository 작성
- [x] create 관련 test
- [x] Member Service, Controller에 create(참여) logic 작성

### 🙋🏻 Halmal

긋입니다~~

**Comment by gimhanul** [comment]
community 생성하며 Member leader 권한으로 만들어야 합니다.
