### ISSUE TITLE
Community 탈퇴

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/Gati-server#30]
### ✨ Describe

user가 community를 탈퇴할 수 있어야 합니다.

### ✅ Tasks

- [x] test
- [x] community 탈퇴 logic
- [x] 탈퇴하며 member 삭제
- [x] member 권한 leader일 때 예외 처리
