### ISSUE TITLE
Community code 부여

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/Gati-server#35]
### ✨ Describe

각 community에 code 를 부여해야 합니다.
-> 검색할 때 용이하게

### ✅ Tasks

- [x] Community Entity 수정
- [x] test 코드 수정 -> 검증
- [x] code 부여 관련 util 생성
