### ISSUE TITLE
Private Community

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/Gati-server#36]
### ✨ Describe

Private community 관련해서 만들어야 댐ㄴ디ㅏ.

### ✅ Tasks

- [x] Community Entity password field 추가
- [x] Private Community 생성 logic에 password 반영
- [x] private community 생성 test
- [x] private community 참여 logic에 password 반영
- [x] private community 참여 test
