### ISSUE TITLE
User 생성

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/Gati-server#4]
### ✨ Describe

회원가입 기능을 구현해야 합니다.

### ✅ Tasks

- [ ] Spring Security Config 작성
- [ ] User Entity 구현 (implements UserDetails)
- [ ] User Repository 작성
- [ ] User create DTO 작성
- [ ] User create Service 작성
- [ ] User create Controller 작성
