### ISSUE TITLE
Authentication 구조 개선

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/Gati-server#87]
### ✨ Describe

현재 cookie에 담아서 날려주는 그런 구조인데, client 측에서 access token을 header에 담아서 날리도록 구조를 변경해야합니다.
또한 refresh token도 어떻게 해야 됨

### ✅ Tasks

- [x] access token 발급 logic
- [x] refresh token 관련 logic
- [x] cookie 이런 친구들 삭제

**Comment by leekyukin** [comment]
이거 설명 좀 해주세요

**Comment by leekyukin** [comment]
우리 프로젝트가 앱이라서 그런건가요

**Comment by gimhanul** [comment]
지금 authentication 과정이

- 발급(로그인): 쿠키에 access token, refresh token 담아서 보냄
- 사용
    1. 프론트 측에서 요청시 요청 마다 쿠키에 access token, refresh token 둘 다 담아서 보냄
    2. access token 만료시 -> 그냥 쿠키에서 refresh token 깜

이런 구조인데 이게 솔직히 원래 동작 과정이랑 안 맞습니다

사용할 때 알고리즘이
1. 프론트 측에서 요청시 요청 마다 access token만 보냄
2. access token 만료시 백엔드에서 프론트에다 만료 됐다고 response 보냄
3. 그럼 프론트에서 최후의 보루로 refresh token 보내고
4. 그럼 백엔드에서 access token 새로 발급해서 보내줌 (refresh token도 만료됐으면 그냥 다시 로그인시키고)
5. 그럼 그 access token 으로 다시 지지고볶고 하는

뭐 이렇게 동작해야 하는데 좀 많이 쉽지 않게 만들어 놨습니다 ㅎㅎ...

그래서 이렇게 Request response 반복해야하니까 request header에 넣어서 만들자는 것이지용

**Comment by leekyukin** [comment]
와우 설명 감사합니다.
근데 원레 refresh token의 용도가 뭔가요

**Comment by gimhanul** [comment]
access token은 보안상 유효 시간을 짧게 해놓고 refresh token은 길게 해놓급니다 (자동로그인st) 그래서 refresh token으로 새로운 access token을 발급시켜주는 거예요

[이 글](https://velog.io/@jkijki12/Jwt-Refresh-Token-적용기) 읽어보면 좋을듯하네용
