### ISSUE TITLE
Board 생성

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/Gati-server#9]
### ✨ Describe

User가 Board를 생성할 수 있어야 합니다.

### ✅ Tasks

- [ ] Board Entity 작성
- [ ] Board Repository 작성
- [ ] Board DTO 작성
- [ ] Board logic 작성(Controller, Service)

### 🙋🏻 Halmal

logic 작성 중 Exception이 예상 되면 global - error - errorCode에 error code 작성하고 exception 만들어서 쓰면 됨!!!
